name: pulse
description: Pulse - Smart Hospital Management System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  firebase_messaging: ^16.0.2
  firebase_analytics: ^12.0.2

  # State Management
  flutter_riverpod: ^3.0.3

  # AI
  google_generative_ai: ^0.4.6

  # UI
  cupertino_icons: ^1.0.8
  flutter_markdown: ^0.7.4+1
  url_launcher: ^6.3.2
  google_fonts: ^6.2.1

  # 3D Rendering
  flutter_cube: ^0.1.1
  model_viewer_plus: ^1.7.2

  # File Handling
  path_provider: ^2.1.4

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1
  http: ^1.5.0
  flutter_dotenv: ^6.0.0

  # Location
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  file_picker: ^10.3.3
  google_maps_flutter: ^2.13.1
  fl_chart: ^1.1.1

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  # Fonts
  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
        - asset: fonts/NotoSans-Bold.ttf
          weight: 700

  # Assets (optional, in case you add images or JSON files later)
  assets:
    - assets/images/
    - assets/updated/
    - fonts/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_pulse.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo_pulse.png"
